### ISSUE TITLE
slxos_linkagg does not handle moving port between LAGs

### ISSUE THREAD

**Issue by LindsayHill** [extremenetworks/ansible-extreme#9]
Consider this contrived playbook:

```yaml
---
- name: LinkAgg Breakage
  hosts: slx01
  gather_facts: no

  tasks:
    - name: Create Port Channel 200
      slxos_linkagg:
        group: 200
        mode: active
        members:
          - Ethernet 0/6
          - Ethernet 0/7

    - name: Now change it to Port Channel 250
      slxos_linkagg:
        group: 250
        mode: active
        members:
          - Ethernet 0/6
          - Ethernet 0/7
```

When this runs it fails:

```shell
PLAY [LinkAgg Breakage] ******************************************************************************

TASK [Create Port Channel 200] ***********************************************************************
changed: [slx01]

TASK [Now change it to Port Channel 250] *************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SLX9140-Leaf1(conf-if-eth-0/6)#
fatal: [slx01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hRLoCw/ansible_module_slxos_linkagg.py\", line 314, in <module>\n    main()\n  File \"/tmp/ansible_hRLoCw/ansible_module_slxos_linkagg.py\", line 307, in main\n    load_config(module, commands)\n  File \"/tmp/ansible_hRLoCw/ansible_modlib.zip/ansible/module_utils/network/slxos/slxos.py\", line 146, in load_config\n  File \"/tmp/ansible_hRLoCw/ansible_modlib.zip/ansible/module_utils/connection.py\", line 146, in __rpc__\nansible.module_utils.connection.ConnectionError: channel-group 250 mode active\r\n%%Error: Port is already aggregated.\r\nSLX9140-Leaf1(conf-if-eth-0/6)# \n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
    to retry, use: --limit @/home/extreme/playbooks/slx_linkagg_break.retry

PLAY RECAP *******************************************************************************************
slx01                      : ok=1    changed=1    unreachable=0    failed=1
```

This is what's happening at the CLI:
```shell
SLX9140-Leaf1# show run int eth 0/7
interface Ethernet 0/7
 channel-group 200 mode active type standard
 lacp timeout long
 shutdown
!
SLX9140-Leaf1# conf t
Entering configuration mode terminal
SLX9140-Leaf1(config)# int eth 0/7
SLX9140-Leaf1(conf-if-eth-0/7)# channel-group 250 mode active type standard
%%Error: Port is already aggregated.
SLX9140-Leaf1(conf-if-eth-0/7)#
```

I believe this should be handled gracefully. It should do the equivalent of this:
```shell
SLX9140-Leaf1# conf t
Entering configuration mode terminal
SLX9140-Leaf1(config)# int eth 0/7
SLX9140-Leaf1(conf-if-eth-0/7)# no channel-group
SLX9140-Leaf1(conf-if-eth-0/7)# channel-group 250 mode active type standard
SLX9140-Leaf1(conf-if-eth-0/7)#
```
